systemd:
  units:
    - name: container-prometheus-node-exporter.service
      enabled: false
      contents: |
        [Unit]
        Description=Prometheus exporter for hardware and OS metrics
        Documentation=https://github.com/prometheus/node_exporter#docker
        Documentation=man:podman-run(1)
        After=network-online.target local-fs.target firewalld.service
        Wants=network-online.target
        StartLimitIntervalSec=40
        StartLimitBurst=5
        RequiresMountsFor=%t/containers
        RequiresMountsFor=/

        [Service]
        TimeoutStartSec=70
        Environment=PODMAN_SYSTEMD_UNIT=%n
        Restart=on-failure
        RestartSec=1s
        ExecStart=/usr/bin/podman run --name=prometheus-node-exporter -d --rm \
                      --cidfile=%t/%N.cid --replace --log-driver journald --cgroups=split \
                      --network=host --sdnotify=conmon --cap-add=sys_time \
                      --label io.containers.autoupdate=registry --pid=host \
                      --mount type=bind,src=/,dst=/host,ro=true,bind-propagation=rslave \
                    quay.io/prometheus/node-exporter:latest \
                      --path.rootfs=/host
        ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%N.cid -t 10
        ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile=%t/%N.cid
        SyslogIdentifier=%N
        KillMode=mixed
        Delegate=yes
        Type=notify
        NotifyAccess=all

        [Install]
        WantedBy=multi-user.target
