name: Ignition Generator

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir -p ./ignition/dist
      - run: |
          podman run --rm -v "${PWD}":/pwd -w /pwd \
            docker.io/mikefarah/yq:latest eval-all '. as $item ireduce ({}; . *+ $item)' \
              ./src/*.yml > ./dist/butane.yml
        working-directory: ignition
      - run: |
          podman run --rm -v "${PWD}":/pwd -w /pwd \
            quay.io/coreos/butane:release --pretty --strict \
              dist/butane.yml > dist/ignition.json
          install LICENSE README.md dist
        working-directory: ignition
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ignition/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
