name: Ignition Generator

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd ignition && mkdir -p dist
      - uses: mikefarah/yq@v4.35.2
        with:
          cmd: |
            yq eval-all '. as $item ireduce ({}; . *+ $item)' \
              ./src/*.yml > ./dist/butane.yml
      - run: |
          podman run --rm -v ${PWD}:/pwd -w /pwd \
            quay.io/coreos/butane:release --pretty --strict \
              dist/butane.yml > dist/ignition.json
          install LICENSE README.md dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
